spring.datasource.url=jdbc:postgresql://stage-db.example.com:5432/icm
spring.datasource.username=stage_user
spring.datasource.password=stage_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
logging.level.root=INFO
